### ISSUE TITLE
if not channel link id

### ISSUE THREAD

**Issue by shiftybit** [seanicus64/BridgeServ#2]
https://github.com/seanicus64/BridgeServ/blob/199ced44309a26e570beb7d908d85031ec07749b/services.py#L407

Edge Case / Logic issue. 
Sometimes the channel ID will be 0.
If the channel ID is 0, the statement will return false, and the function execution will return.

**Comment by seanicus64** [comment]
Good catch.  Changed it to "if channel_link_id is not None"

**Comment by seanicus64** [comment]
"is not None" introduced a bug So I changed it to "is None", which is how it should have been.
